spring.datasource.url=${ATLAS_DB_URL}
spring.datasource.username=${ATLAS_DB_USER}
spring.datasource.password=${ATLAS_DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
