package com.atlas.command;

public enum CommandErrorCode {

    DEVICE_UNREACHABLE,
    DEVICE_RETIRED,
    ADAPTER_UNAVAILABLE,
    UNSUPPORTED_ACTION,
    INVALID_PARAMETER,
    SAFETY_LIMIT_EXCEEDED,
    RATE_LIMITED,
    LOOP_GUARD_TRIPPED,
    NOT_AUTHORIZED,
    DEVICE_REJECTED,
    INTERNAL_ERROR
}